name: Push new version to dist branch
on:
  push:
    branches:
      - main
  workflow_call:
  # pull_request:
  # branches:
  # - main

jobs:
  deploy:
    name: Push
    runs-on: ubuntu-latest
    env:
      TARGET_BRANCH: dist
    permissions:
      contents: write
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
          cache-dependency-path: yarn.lock

      - name: Configure Git
        run: |
          git config --global user.name "Github Actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git pull origin HEAD
          git worktree add -B $TARGET_BRANCH dist origin/$TARGET_BRANCH

      - name: Install Dependencies and Build
        run: |
          yarn
          yarn build:prod

      - name: Push New Version
        run: |
          export SHORT_SHA=$(git rev-parse --short HEAD)
          cd dist
          git add .
          git diff-index --quiet HEAD || git commit -am "Update to output generated at $SHORT_SHA"
          git push origin $TARGET_BRANCH
