name: Push new version to dist branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Push
    runs-on: ubuntu-latest
    env:
      TARGET_BRANCH: dist
    permissions:
      contents: write
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Node.js (v20)
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Configure Git
        run: |
          git config --global user.name "Github Actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git pull origin HEAD
          git worktree add -B $TARGET_BRANCH dist origin/$TARGET_BRANCH

      - name: Install Dependencies and Build
        run: |
          pnpm install --frozen-lockfile
          pnpm build:prod

      - name: Push New Version
        run: |
          export SHORT_SHA=$(git rev-parse --short HEAD)
          cd dist
          git add .
          git diff-index --quiet HEAD || git commit -am "Update to output generated at $SHORT_SHA"
          git push origin $TARGET_BRANCH
